blog/urls.py
from django.urls import path

from .views import BlogDetailView, BlogListView
from .feeds import BlogRssFeed, BlogAtomFeed

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('blog/<str:slug>', BlogDetailView.as_view(), name="detail"),
    path('feed/rss/', BlogRssFeed(), name="rss-feed"),
    path('feed/atom/', BlogAtomFeed(), name="blog-atom-feed"),
]

people/urls.py
from django.urls import path

from .views import PeopleView

app_name = "people"

urlpatterns = [
    path('', PeopleView.as_view(), name='index'),
]

presentations/urls.py
from django.conf.urls import url

from .views import PresentationsView


app_name = 'presentations'


urlpatterns = [
    url(r'^$', PresentationsView.as_view(), name='index'),
]

pyist/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.sitemaps.views import index, sitemap
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from blog.sitemap import BlogSitemap

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap,
}

urlpatterns = [
    # apps
    path('', include('blog.urls', namespace="blog")),
    path('people/', include('people.urls')),
    path('presentations/', include('presentations.urls')),
    path('sitemap.xml', index, {'sitemaps': sitemaps}),
    # path('sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}),

    # third party apps
    # path(r'^comments/', include('djangospam.cookie.urls')),

    # admin
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suggestpresentation/urls.py
from django.conf.urls import include, url
from .views import CreateSuggestPresentation

app_name = 'suggestpresentation'

urlpatterns = [
    url('', CreateSuggestPresentation.as_view(), name="index"),
]

blog/models.py
# coding: utf-8

from django.db import models
from django.utils.encoding import smart_text, python_2_unicode_compatible
from django.conf import settings

from markitup.fields import MarkupField

from .managers import BlogManager


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = MarkupField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    is_published = models.BooleanField(default=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    objects = BlogManager()

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return smart_text(self.title)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:detail', args=[str(self.slug)])

people/models.py
# coding: utf-8

import codecs

from django.db import models
from django.utils.encoding import smart_text, python_2_unicode_compatible

from .managers import PeopleManager


@python_2_unicode_compatible
class Person(models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name='Ad ve Soyad')
    email = models.EmailField(
        max_length=255,
        help_text='Gravatar için gerekmektedir, sitede gözükmeyecektir.')
    blog_link = models.URLField(max_length=255, verbose_name="Blog URL")
    twitter_username = models.CharField(
        max_length=255, blank=True,
        null=True, verbose_name='Twitter',
        help_text='Twitter kullanıcı adınızı giriniz.')
    github_username = models.CharField(
        max_length=255, blank=True, null=True, verbose_name='GitHub',
        help_text='GitHub kullanıcı adınızı giriniz.')
    is_active = models.BooleanField(default=True)

    objects = PeopleManager()

    class Meta:
        verbose_name_plural = "People"

    def __str__(self):
        return smart_text(self.name)

    def badge(self):
        if codecs.encode(self.email, "rot13") == "uhfrlvanyo@tznvy.pbz":
            return "huseyinalbing"

presentations/models.py
from django.db import models
from django.utils.encoding import smart_text, python_2_unicode_compatible


@python_2_unicode_compatible
class Presentation(models.Model):
    title = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    date = models.DateField()
    link = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return smart_text(self.title)

suggestpresentation/models.py
from django.db import models

# Create your models here.

class suggest(models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name='Ad ve Soyad')
    email = models.EmailField(
        max_length=255,)
    content = models.TextField(verbose_name="Öneriniz")

    class Meta:
        verbose_name_plural = "Suggestions"

    def __str__(self):
        return self.content

people/forms.py
from django import forms

from .models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ("name", "email", "blog_link", "twitter_username",
                  "github_username")

presentations/forms.py
from django.forms import ModelForm

from presentations.models import PresentationRequest


class PresentationRequestForm(ModelForm):
    class Meta:
        model = PresentationRequest
        fields = ('presenter_name', 'presenter_email',
                  'presenter_twitter_username', 'presenter_github_username',
                  'presentation_title', 'presentation_type',
                  'presentation_duration', 'presentation_content')

suggestpresentation/forms.py
from django import forms
from .models import suggest

class suggestPresentationForm(forms.ModelForm):
    class Meta:
        model = suggest
        fields = '__all__'

blog/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.conf import settings

from .models import Post


class BlogListView(ListView):
    template_name = 'index.html'
    queryset = Post.objects.active()
    paginate_by = settings.BLOG['LIMIT']

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['page'] = 'home'
        return context


class BlogDetailView(DetailView):
    template_name = "blog/blog_detail.html"
    queryset = Post.objects.active()

people/views.py
from django.urls import reverse
from django.views.generic import ListView

from people.forms import PersonForm
from people.models import Person


class PeopleView(ListView):
    queryset = Person.objects.active()
    form_class = PersonForm
    success_message = 'Kişi başarıyla eklendi.'

    def get_success_url(self):
        return reverse("people:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page"] = "people"
        context["page_title"] = "İnsanlar"

        return context

presentations/views.py
from django.views.generic import ListView

from .models import Presentation


class PresentationsView(ListView):
    model = Presentation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["page"] = "presentation"
        context["page_title"] = "Sunumlar"

        return context

suggestpresentation/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from .forms import suggestPresentationForm
from django.views.generic import CreateView
from .models import suggest

# Create your views here.

class CreateSuggestPresentation(CreateView):
    model = suggest
    form_class = suggestPresentationForm
    success_message = "Öneriniz başarıyla iletildi."

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super(CreateSuggestPresentation, self).form_valid(form)

    def get_success_url(self):
        return reverse("suggestpresentation:index")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}{{ BLOG_SETTINGS.TITLE }}{% endblock %}
        {% if page_title %}&mdash; {{ page_title }}{% endif %}
    </title>
    <meta name="description" content="{{ BLOG_SETTINGS.DESCRIPTION }}">
    <link rel="shortcut icon" type="image/favicon" href="{% static 'images/favicon.ico' %}">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link href="{% url 'blog:rss-feed' %}" type="application/rss+xml" rel="alternate" />
    <!--[if lt IE 9]><script src="{% static 'js/html5shiv.js' %}"></script><![endif]-->

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    {% block head %}
    {% endblock head %}
</head>
<body>
    <!--
    [if lt IE 7]>
        <p class="chromeframe">
            You are using an outdated browser.
            <a href="http://browsehappy.com/">Upgrade your browser today</a>
            or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a>
            to better experience this site.
        </p>
    <![endif]
    -->
    <div class="collapse" id="pyistanbul">
        <div class="container fixed-info">
            <div class="row">
                <div class="col-md-4 info what">
                    <div class="sub-title">Nedir?</div>
                    <p>İstanbul'daki Python programcıları topluluğudur. Eğer Python ilginizi çekiyorsa siz de bu topluluğa katılabilirsiniz.</p>
                </div>
                <div class="col-md-4 info contact">
                    <div class="sub-title">Nasıl iletişim kurabilirim?</div>
                    <p>Her gün Freenode'daki <a href="#">#pyistanbul</a> kanalında buluşuyoruz.</p>
                </div>
                <div class="col-md-4 info support">
                    <div class="sub-title">Desteğe ihtiyacım var</div>
                    <p>IRC'de ya da python-istanbul e-posta listesinde sorularınızı sorabilirsiniz.</p>
                </div>
            </div>
        </div>
    </div>
    <header class="{% if page == 'home' %}_home{% endif %}">
        <nav class="navbar navbar-expand-sm">
            <div class="mx-auto d-sm-flex d-block flex-sm-nowrap">
                <div class="text-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a data-toggle="collapse" href="#pyistanbul">NEDİR?</a>
                        </li>
                        <li class="nav-item {% if page == 'presentation' %}active{% endif %}">
                            <a href="{% url 'presentations:index' %}">SUNUMLAR</a>
                        </li>
                        <li class="nav-item logo">
                            <a href="{% url 'blog:home' %}">
                                <img src="{% static 'images/logo.svg' %}" alt="Pyistanbul">
                            </a>
                        </li>
                        <li class="nav-item {% if page == 'people' %}active{% endif %}"><a href="{% url 'people:index' %}">İNSANLAR</a></li>
                        <li class="nav-item {% if page == 'blog' %}active{% endif %}"><a href="#">BLOG</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block cover %}
    {% endblock %}

    {% block content %}

    {% endblock content %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="col-title">NEWSLETTER</div>
                    <form>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Type your email address"> 
                        </div>
                        <button class="btn btn-block">Send</button>
                    </form>
                </div>
                <div class="col-md-4">
                    <div class="col-title">GITHUB</div>
                    <a class="github" href="#">pyistanbul</a>
                </div>
                <div class="col-md-4">
                    <div class="col-title">CONNECT WITH US</div>
                </div>
            </div>
            <div class="row justify-content-center copyright"><span>2015 © PyIstanbul</span></div>
        </div>
    </footer>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36021524-2', 'pyistanbul.org');
      ga('send', 'pageview');
    </script>
</body>
</html>

templates/base_page.html
{% extends "base.html" %}

{% block cover %}
<div class="cover">
	<div class="container">
		<div class="row">
			<h2>{% if page_title %}{{ page_title }}{% endif %}</h2>
		</div>
	</div>
</div>
{% endblock cover %}

{% block content %}
<div class="page">
	<div class="container">
		{% block page %}
	    {% endblock page %}
	</div>
</div>
{% endblock content %}

templates/blog/blog_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="post">
        <header>
            <time>{{ object.created_at|date:"j F Y" }}</time>
            <h3>{{ object.title }}</h3>
        </header>
        {% autoescape off %}
          {{ object.description.rendered }}
        {% endautoescape %}
    </div>

    {% if BLOG_SETTINGS.USE_DISQUS %}
    <div id="comments" class="post box">
      <div class="content-space">
        {% include "blog/partials/disqus.html" %}
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/blog/partials/disqus.html
<div id="disqus_thread"></div>

<script type="text/javascript">
var disqus_shortname = '{{ BLOG_SETTINGS.DISQUS_USERNAME }}';
(function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

templates/djangospam/cookieform.html
<div hidden>
    <form method="post" action="{% url 'djangospam.cookie.views.spammer_view' %}">
        <label for="honeypot">Honeypot</label>
            <input id="honeypot" type="text" name="honeypot">
        <label for="name">Name</label>
            <input id="name" type="text" name="name">
        <label for="email">E-mail</label>
            <input id="email" type="text" name="email">
        <label for="url">Website (optional)</label>
            <input id="url" type="text" name="url">
        <label for="comment">Your comment</label>
            <textarea id="comment" name="comment"></textarea>
        {% csrf_token %}
        <input type="submit" value="Send">
    </form>
</div>

templates/hakkimizda.html
{% extends "base.html" %}

{% block title %}Python İstanbul Nedir?{% endblock %}

{% block content %}
    <div class="post">
        <header>
            <h3>Python İstanbul Nedir?</h3>
        </header>
    </div>

    <div id="comments" class="post box">
      <div class="content-space">
        <p>
            İstanbul'daki Python programcıları topluluğu olarak 2010 yılından bu yana çeşitli etkinlikler düzenledik.
            Yaptığımız etkinliklere sunumlar sayfasından göz atabilirsiniz.
        </p>
          <P>Bunun dışında,</P>
          <ul>
              <li>Tek günlük mini bir konferans yaptık</li>
              <li>Julython hackathon'ı düzenledik</li>
              <li>Django sprint'i düzenledik</li>
              <li>Jstanbul ile beraber JsPyConf'u düzenledik</li>
          </ul>
      </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="home">
        <div class="no-event">
            <div class="newsletter-title">HABERDAR OL</div>
            <div class="newsletter-text">
                Şu an planlanmış bir etkinliğimiz yok.
                <span>Gelecekteki etkinliklerden anında haberdar olmak için eposta adresini bırak.</span>
            </div>
            <div class="newsletter-form clearfix">
                <form>
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email adresinizi girin">
                    </div>
                    <button>Gönder</button>
                </form>
            </div>
            <div class="submit-info">E-posta listemize başarıyla kaydoldunuz.</div>
        </div>
    </div>

    <div class="featured-events">
        <div class="container">
            <div class="row">
                <div class="event-years">
                    <div class="sub-title">ETKİNLİK ARŞİVİ</div>
                    <ul class="years">
                        <li class="active"><a href="#">2018</a></li>
                        <li><a href="#">2017</a></li>
                        <li><a href="#">2016</a></li>
                        <li><a href="#">2015</a></li>
                        <li><a href="#">2014</a></li>
                        <li><a href="#">2013</a></li>
                    </ul>
                </div>
            </div>
            <div class="row event-box-title">GEÇMİŞ ETKİNLİKLER</div>
            <div class="row event-boxes">
                <div class="event-box">
                    <div class="row">
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                    </div>
                    <div class="event-details">
                        <div class="date">
                            11 TEMMUZ 2015, ÇARŞAMBA
                        </div>
                        <div class="event-title">
                            Pyİstanbul 11 Temmuz Etkinliği
                        </div>
                        <div>
                            <div class="location">
                                <a href="#">
                                    Prisync
                                </a>
                            </div>
                            <div class="detail">
                                <a href="#">
                                    Detaylar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="event-box">
                    <div class="row">
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                        <div class="col-md-4 no-padding">
                            <img src="http://lorempixel.com/150/150/" alt="">
                        </div>
                    </div>
                    <div class="event-details">
                        <div class="date">
                            11 TEMMUZ 2015, ÇARŞAMBA
                        </div>
                        <div class="event-title">
                            Pyİstanbul 11 Temmuz Etkinliği
                        </div>
                        <div>
                            <div class="location">
                                <a href="#">
                                    Prisync
                                </a>
                            </div>
                            <div class="detail">
                                <a href="#">
                                    Detaylar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/people/person_detail.html
{% extends "base.html" %}

{% load gravatar %}
{% load people_extras %}

{% block title %}{{ block.super }} - {{ object.username }}{% endblock %}

{% block content %}
    <div style="float: left">
        {% gravatar object.email 220 %}

        {% if object.links.count > 0 %}
            <div>
                {% for link in object.links.all %}
                    <a href="{{ link.link }}" style="color:#000; text-decoration: none;" target="_blank">
                        {% fontawesome link.account_type '2x' %}
                    </a>
                {% endfor %}
            </div>
        {% endif %}

        {% if user.is_authenticated and user.username == object.username %}
            <a href="{% url 'account_change_password' %}" class="button">
                Parola Değiştir
            </a>
        {% endif %}
    </div>
    <div style="float:left; margin-left: 20px; font-size: 20px">
        {% if object.get_full_name %}
            {{ object.get_full_name }}
        {% endif %}

        <a href="{% url 'people:detail' object.username %}">
            @{{ object.username }}
        </a>

        {% if object.presentations.count > 0 %}
            <div class="presentations" style="width:200px; margin-top: 10px">
                <ul>
                {% for presentation in object.presentations.all %}
                    <li>
                        <a href="{{ presentation.link }}" target="_blank">
                            {{ presentation.title }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}

    </div>
{% endblock content %}

templates/people/person_form.html
{% extends "base.html" %}

{% block content %}
    <h3>Yeni kişi</h3>
    <form action="{% url "people:new" %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="line">
            {{ field.errors }}
            {{ field.label_tag }}
            <div class="field">
                {{ field }}
                <p class="help">{{ field.help_text }}</p>
            </div>
        </div>
    {% endfor %}
    <footer>
        <input class="button" type="submit" value="Kaydet">
    </footer>
    </form>

{% endblock %}

templates/people/person_list.html
{% extends "base_page.html" %}

{% load gravatar %}

{% block page %}
    <div class="people top-shift">
        <div class="row">
            {% for person in person_list %}
            <div class="col-md-3 person">
                {% gravatar person.email 100 %}
                <div class="p-name">{{ person.name }}</div>
                <div class="p-company">software developer <span>@adphorus</span></div>
                <ul class="p-social">
                    {% if person.twitter_username %}
                        <li class="a-twitter">
                            <a href="http://twitter.com/{{ person.twitter_username }}"></a>
                        </li>
                    {% endif %}
                    {% if person.github_username %}
                        <li class="a-github">
                            <a href="http://github.com/{{ person.github_username }}"></a>
                        </li>
                    {% endif %}
                    {% if person.blog_link %}
                        <li class="a-blog">
                            <a href="{{ person.blog_link }}"></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            {% endfor %}
            <div class="col-md-3 person">
                <div class="new-person-btn" data-toggle="modal" data-target="#new-person-form"></div>
                <div class="p-name">Yeni Kişi Ekle</div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="new-person-form" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Yeni Kişi</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'people:index' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="form-name">Ad ve Soyad</label>
                            <input type="text" class="form-control" id="name" placeholder="Ad ve Soyad">
                        </div>
                        <div class="form-group">
                            <label for="form-email">Email</label>
                            <input type="email" class="form-control" id="form-email" aria-describedby="emailHelp" placeholder="example@domain.com">
                            <small id="emailHelp" class="form-text text-muted">Gravatar için gerekmektedir, sitede gözükmeyecektir.</small>
                        </div>
                        <div class="form-group">
                            <label for="form-blog">Blog URL</label>
                            <input type="text" class="form-control" id="form-blog" placeholder="http://">
                        </div>
                        <div class="form-group">
                            <label for="form-twitter">Twitter</label>
                            <input type="text" class="form-control" id="form-twitter" placeholder="@pyistanbul">
                        </div>
                        <div class="form-group">
                            <label for="form-github">Github</label>
                            <input type="text" class="form-control" id="form-github" placeholder="@pyistanbul">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/presentations/presentation_list.html
{% extends "base_page.html" %}


{% block page %}
    <div class="events top-shift">
        <div class="row">
            <div class="card-columns">
                {% regroup presentation_list by date as presentations %}
                {% for date in presentations %}
                <div class="event card">
                    <div class="card-body">
                        <div class="event-title">Pyİstanbul 11 Temmuz Etkinliği</div>
                        <!-- 
                        TODO: Profile entegrasyonu sonrasi burasinin duzenlenmesi gerekiyor

                        <div class="speakers">
                            <ul>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid logo" src="http://lorempixel.com/86/86/people/">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid logo" src="http://lorempixel.com/86/86/people/">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid logo" src="http://lorempixel.com/86/86/people/">
                                    </a>
                                </li>
                            </ul>
                        </div>
                        -->
                        <div class="presentations">
                            {% for presentation in date.list %}
                            <div class="presentation">
                                <a href="{{ presentation.link }}" target="_blank">
                                    <div class="presentation-title">{{ presentation.title }}</div>
                                </a>
                                <div class="speaker-name">{{ presentation.owner }}</div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/presentations/presentation_request_form.html
{% extends "base.html" %}

{% block content %}
    <h3>Sunum Başvuru Formu</h3>
    {% include 'djangospam/cookieform.html' %}
    <form action="{% url "presentations:request" %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="line">
            {{ field.errors }}
            {{ field.label_tag }}
            <div class="field">
                {{ field }}
                <p class="help" style="display: inline; margin-left: 0;">{{ field.help_text }}</p>
            </div>
        </div>
    {% endfor %}
    <footer>
        <input class="button" type="submit" value="Kaydet">
    </footer>
    </form>
{% endblock %}

templates/simplewiki/base.html
{% extends "base.html" %}

{% block content %}{% endblock %}

templates/suggestpresentation/suggest_form.html
{% extends "base.html" %}

{% block content %}
    <h3>Sunum önerilerinizi bize iletebilirsiniz</h3>
    <form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="line">
            {{ field.errors }}
            {{ field.label_tag }}
            <div class="field">
                {{ field }}
                <p class="help">{{ field.help_text }}</p>
            </div>
        </div>
    {% endfor %}
    <footer>
        <input class="button" type="submit" value="Kaydet">
    </footer>
    </form>

{% endblock %}